/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_content_delivery_bucket": "rontend-20250402123026-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-north-1",
    "aws_content_delivery_url": "https://d1b2ywmhi5kwcs.cloudfront.net",
    "aws_cloud_logic_custom": [
        {
            "name": "apic64d4410",
            "endpoint": "https://sc13z5uyt5.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
